### ISSUE TITLE
inav bb explorer misreads files with missing fields

### ISSUE THREAD

**Issue by laurentopia** [iNavFlight/blackbox-log-viewer#39]
open attached bb produced by inav (a bug I think) and get noise

![image](https://user-images.githubusercontent.com/26075468/65804864-3f6c6f80-e138-11e9-8ba5-3b1afc08a896.png)
![image](https://user-images.githubusercontent.com/26075468/65804868-44c9ba00-e138-11e9-803a-28730c5720dc.png)
[LOG00001.zip](https://github.com/iNavFlight/blackbox-log-viewer/files/3664665/LOG00001.zip)

**Comment by namirda** [comment]
I think I may have the same problem as @laurentopia above.  

Using INAV 2.2.1, and BB Explorer 3.3 I get pictures like the attached. 

All curves look OK except the I2C devices Mag and Baro which have the blocky appearance as shown. 

The I2C curves look smooth when viewed in the Sensors tab of INav.

However, I am having trouble calibrating the compass in INav and so am not sure if the problem is with my I2C devices or if there is a bug in BB Explorer.  I suspect the latter - it looks to me as if BB Explorer is decoding the I2C values incorrectly.

Any thoughts?
![Capture](https://user-images.githubusercontent.com/18044324/67724183-1b57c300-fa43-11e9-9df5-f36b98b5075f.JPG)
